pipeline {
    agent none
    options { skipDefaultCheckout(true) }
    stages {
        stage('Build and Test') {
            agent {
                docker {
                    image 'node:12.16.1-alpine'
                }
            }
            options { skipDefaultCheckout(false) }
            steps {
                script{
                    try {
                        mattermostSend (
                            color: "#2A42EE", 
                            message: "Build STARTED: ${env.JOB_NAME} #${env.BUILD_NUMBER} (<${env.BUILD_URL}|Link to build>)"
                        )
                        dir("frontend"){
                            sh 'npm -v'
                            sh 'npm install'
                            sh 'npm run build'
                        }
                        currentBuild.result = "SUCCESS"
                    } catch(e) {
                        currentBuild.result = "FAILURE"
                    } finally {
                        if(currentBuild.result == "FAILURE") {
                            mattermostSend (
                                color: "danger", 
                                message: "Build FAILED: ${env.JOB_NAME} #${env.BUILD_NUMBER} (<${env.BUILD_URL}|Link to build>)"
                            )
                        } else {
                            mattermostSend (
                                color: "good", 
                                message: "Build SUCCESS: ${env.JOB_NAME} #${env.BUILD_NUMBER} (<${env.BUILD_URL}|Link to build>)"
                            )
                        }                            
                    } 
                }
            }
        }
        stage('Docker build') {
            agent any
            steps {
                sh 'docker build -t vue-client-image:latest ./frontend'
            }
        }
        stage('Docker run') {
            agent any
            steps {
                sh 'docker ps -f name=vue-client-container -q | xargs --no-run-if-empty docker container stop'
                sh 'docker container ls -a -fname=vue-client-container -q | xargs -r docker container rm'
                sh 'docker rmi $(docker images -f "dangling=true" -q) -f'
                sh 'docker run -d --name vue-client-container -p 80:80 vue-client-image:latest'
            }
        }
    }
}
